/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fees_management_system;

import java.awt.*;
import java.awt.print.*;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    public void getRecords() {

        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/fees_management", "root", "root");
            String sql = "select * from fees_details order by reciept_no desc fetch first 1 rows only";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();

            txt_RecieptNo.setText(rs.getString("reciept_no"));
            txt_StudentName.setText(rs.getString("student_name"));
            txt_StudentRollNo.setText(rs.getString("roll_no"));

            txt_PaymentMode.setText(rs.getString("payment_mode"));
            String paymentMode = rs.getString("payment_mode");

            if (paymentMode.equalsIgnoreCase("Cheque")) {
                lbl_ChequeNo_DDNo_TransactionId.setText("Cheque No. : ");
                txt_ChequeNo_DDNo_TransactionId.setText(rs.getString("cheque_no"));
                txt_BankName.setText(rs.getString("bank_name"));
            } else if (paymentMode.equalsIgnoreCase("DD")) {
                lbl_ChequeNo_DDNo_TransactionId.setText("DD No. : ");
                txt_ChequeNo_DDNo_TransactionId.setText(rs.getString("dd_no"));
                txt_ChequeNo_DDNo_TransactionId.setText(rs.getString("bank_name"));
            } else if (paymentMode.equalsIgnoreCase("Online")) {
                lbl_ChequeNo_DDNo_TransactionId.setText("Transaction Id : ");
                txt_ChequeNo_DDNo_TransactionId.setText(rs.getString("transaction_id"));
                lbl_BankName.setVisible(false);
                txt_BankName.setVisible(false);
            } else if (paymentMode.equalsIgnoreCase("Cash")) {
                lbl_ChequeNo_DDNo_TransactionId.setVisible(false);
                txt_ChequeNo_DDNo_TransactionId.setVisible(false);
                lbl_BankName.setVisible(false);
                txt_BankName.setVisible(false);
            }

            txt_CourseName.setText(rs.getString("course_name"));
            txt_Date.setText(rs.getString("t_date"));
            txt_GSTIN.setText(rs.getString("gstin"));
            txt_Amount.setText(rs.getString("amount"));
            txt_TotalAmount.setText(rs.getString("total_amount"));
            txt_CGST.setText(rs.getString("cgst"));
            txt_SGST.setText(rs.getString("sgst"));
            txt_TotalInWords.setText(rs.getString("total_in_words"));
            txt_Remark.setText(rs.getString("remark"));
            txt_Year1.setText(rs.getString("year1"));
            txt_Year2.setText(rs.getString("year2"));
            txt_Semester.setText(rs.getString("semester"));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        panelToPrint = new javax.swing.JPanel();
        panelRecieptLogo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRecieptDate = new javax.swing.JPanel();
        lbl_RecieptNo = new javax.swing.JLabel();
        txt_RecieptNo = new javax.swing.JLabel();
        lbl_PaymentMode = new javax.swing.JLabel();
        txt_PaymentMode = new javax.swing.JLabel();
        lbl_ChequeNo_DDNo_TransactionId = new javax.swing.JLabel();
        txt_ChequeNo_DDNo_TransactionId = new javax.swing.JLabel();
        lbl_BankName = new javax.swing.JLabel();
        txt_BankName = new javax.swing.JLabel();
        lbl_StudentName = new javax.swing.JLabel();
        txt_StudentName = new javax.swing.JLabel();
        lbl_Year = new javax.swing.JLabel();
        txt_Year1 = new javax.swing.JLabel();
        lbl_Year_Desh = new javax.swing.JLabel();
        txt_Year2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_StudentRollNo = new javax.swing.JLabel();
        txt_SrNo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_SrNo = new javax.swing.JLabel();
        lbl_Head = new javax.swing.JLabel();
        lbl_Amount = new javax.swing.JLabel();
        txt_GSTIN = new javax.swing.JLabel();
        txt_CourseName = new javax.swing.JLabel();
        lbl_CGST = new javax.swing.JLabel();
        lbl_SGST = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JLabel();
        txt_CGST = new javax.swing.JLabel();
        txt_SGST = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_TotalAmount = new javax.swing.JLabel();
        txt_TotalInWords = new javax.swing.JLabel();
        lbl_TotalInWords = new javax.swing.JLabel();
        lbl_GSTIN = new javax.swing.JLabel();
        txt_StudentRollNo = new javax.swing.JLabel();
        lbl_ReceiverSignature = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_RecieptNoLogoPrefix = new javax.swing.JLabel();
        lbl_Semester = new javax.swing.JLabel();
        txt_Semester = new javax.swing.JLabel();
        lbl_Remark = new javax.swing.JLabel();
        txt_Remark = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        txt_Date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelsideBar.setBackground(new java.awt.Color(245, 245, 245));
        panelsideBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 10));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnHome.setBackground(new java.awt.Color(0, 102, 153));
        btnHome.setFont(new java.awt.Font("Comic Sans MS", 3, 28)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\home.png")); // NOI18N
        btnHome.setText(" HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panelBack.setBackground(new java.awt.Color(51, 51, 51));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 3, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\left-arrow.png")); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(204, 0, 51));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\logout.png")); // NOI18N
        jLabel9.setText("Logout");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\print_reciept_logo.png")); // NOI18N
        jLabel1.setText("  Print Reciept");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelEdit.setBackground(new java.awt.Color(0, 102, 255));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnEdit.setBackground(new java.awt.Color(0, 102, 153));
        btnEdit.setFont(new java.awt.Font("Comic Sans MS", 3, 28)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\edit2.png")); // NOI18N
        btnEdit.setText(" EDIT");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panelPrint.setBackground(new java.awt.Color(3, 53, 106));
        panelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnPrint.setBackground(new java.awt.Color(0, 102, 153));
        btnPrint.setFont(new java.awt.Font("Comic Sans MS", 3, 28)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\my icons\\printer-.png")); // NOI18N
        btnPrint.setText(" PRINT");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPrintLayout = new javax.swing.GroupLayout(panelPrint);
        panelPrint.setLayout(panelPrintLayout);
        panelPrintLayout.setHorizontalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );
        panelPrintLayout.setVerticalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelsideBarLayout = new javax.swing.GroupLayout(panelsideBar);
        panelsideBar.setLayout(panelsideBarLayout);
        panelsideBarLayout.setHorizontalGroup(
            panelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsideBarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelsideBarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        panelsideBarLayout.setVerticalGroup(
            panelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsideBarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(panelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(panelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelToPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 160, 200), 12));
        panelToPrint.setPreferredSize(new java.awt.Dimension(1072, 855));
        panelToPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRecieptLogo.setBackground(new java.awt.Color(245, 245, 245));
        panelRecieptLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 10));
        panelRecieptLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\MAJOR PROJECT DATABASE\\Icon_Images\\SRIT_LOGO.png")); // NOI18N
        panelRecieptLogo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 23, -1, 133));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("SHRI RAM INSTITUTE OF TECHNOLOGY");
        panelRecieptLogo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 23, -1, 36));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 204));
        jLabel13.setText("Approved by AICTE New Delhi & Govt. of M.P.");
        panelRecieptLogo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 66, -1, -1));

        jLabel14.setText("(Affiliated to R.G.P.V.V - University of Technology of Maadhya Pradesh)");
        panelRecieptLogo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 99, -1, -1));

        jLabel15.setText("ISO 9001 : 2000 Certified Institution");
        panelRecieptLogo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 122, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 204));
        jLabel16.setText("Near ITI, MADHOTAL, JABALPUR - 482002 (M.P.)");
        panelRecieptLogo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 145, -1, -1));

        panelToPrint.add(panelRecieptLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 1027, 180));

        panelRecieptDate.setBackground(new java.awt.Color(235, 235, 235));
        panelRecieptDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 10));
        panelRecieptDate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_RecieptNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_RecieptNo.setForeground(new java.awt.Color(245, 0, 31));
        lbl_RecieptNo.setText("Reciept No. : ");
        panelRecieptDate.add(lbl_RecieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 42, -1, 35));

        txt_RecieptNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_RecieptNo.setText(" ");
        panelRecieptDate.add(txt_RecieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 42, 180, 35));

        lbl_PaymentMode.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_PaymentMode.setForeground(new java.awt.Color(245, 0, 31));
        lbl_PaymentMode.setText("Payment Mode : ");
        panelRecieptDate.add(lbl_PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 84, -1, 35));

        txt_PaymentMode.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_PaymentMode.setText("Payment Mode : ");
        panelRecieptDate.add(txt_PaymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 84, 280, 35));

        lbl_ChequeNo_DDNo_TransactionId.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_ChequeNo_DDNo_TransactionId.setForeground(new java.awt.Color(245, 0, 31));
        lbl_ChequeNo_DDNo_TransactionId.setText("Transaction Id : ");
        panelRecieptDate.add(lbl_ChequeNo_DDNo_TransactionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 126, -1, 35));

        txt_ChequeNo_DDNo_TransactionId.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_ChequeNo_DDNo_TransactionId.setText("Transaction Id ");
        panelRecieptDate.add(txt_ChequeNo_DDNo_TransactionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 126, 300, 35));

        lbl_BankName.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_BankName.setForeground(new java.awt.Color(245, 0, 31));
        lbl_BankName.setText("Bank Name : ");
        panelRecieptDate.add(lbl_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 174, -1, 35));

        txt_BankName.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_BankName.setText("Bank Name :");
        panelRecieptDate.add(txt_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 174, 346, 35));

        lbl_StudentName.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_StudentName.setForeground(new java.awt.Color(245, 0, 31));
        lbl_StudentName.setText("Student Name : ");
        panelRecieptDate.add(lbl_StudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 216, -1, 35));

        txt_StudentName.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_StudentName.setText("Student Name : ");
        panelRecieptDate.add(txt_StudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 216, 380, 35));

        lbl_Year.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Year.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Year.setText("Year : ");
        panelRecieptDate.add(lbl_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, 35));

        txt_Year1.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Year1.setText("Year1 ");
        panelRecieptDate.add(txt_Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 10, -1, 35));

        lbl_Year_Desh.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Year_Desh.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Year_Desh.setText("-");
        panelRecieptDate.add(lbl_Year_Desh, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 10, -1, 35));

        txt_Year2.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Year2.setText("Year2 ");
        panelRecieptDate.add(txt_Year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 10, -1, 35));

        jLabel17.setText("Ph. No. : 0761 - 2640291, 94 Fax No. : 2640294 Mobile - 9300104815");
        panelRecieptDate.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, -1, -1));

        lbl_StudentRollNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_StudentRollNo.setForeground(new java.awt.Color(245, 0, 31));
        lbl_StudentRollNo.setText("Enrollment No. : ");
        panelRecieptDate.add(lbl_StudentRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 216, -1, 35));

        txt_SrNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_SrNo.setText("1. ");
        panelRecieptDate.add(txt_SrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 327, -1, 35));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 153));
        panelRecieptDate.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 258, 943, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));
        panelRecieptDate.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 310, 943, 10));

        lbl_SrNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_SrNo.setForeground(new java.awt.Color(245, 0, 31));
        lbl_SrNo.setText("Sr No.");
        panelRecieptDate.add(lbl_SrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 275, -1, -1));

        lbl_Head.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Head.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Head.setText("Head ");
        panelRecieptDate.add(lbl_Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 275, -1, -1));

        lbl_Amount.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Amount.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Amount.setText("Amount ");
        panelRecieptDate.add(lbl_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 275, -1, -1));

        txt_GSTIN.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_GSTIN.setText("GSTIN : ");
        panelRecieptDate.add(txt_GSTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 180, 35));

        txt_CourseName.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_CourseName.setText("Course (Branch) Name ");
        panelRecieptDate.add(txt_CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 327, 421, 35));

        lbl_CGST.setFont(new java.awt.Font("Calisto MT", 3, 16)); // NOI18N
        lbl_CGST.setForeground(new java.awt.Color(245, 0, 31));
        lbl_CGST.setText("CGST   [9%]  -");
        panelRecieptDate.add(lbl_CGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 369, -1, 35));

        lbl_SGST.setFont(new java.awt.Font("Calisto MT", 3, 16)); // NOI18N
        lbl_SGST.setForeground(new java.awt.Color(245, 0, 31));
        lbl_SGST.setText("SGST   [9%]  -");
        panelRecieptDate.add(lbl_SGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 411, -1, 35));

        txt_Amount.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Amount.setText("Amount");
        panelRecieptDate.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 327, 160, 35));

        txt_CGST.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_CGST.setText("Amount");
        panelRecieptDate.add(txt_CGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 369, 160, 35));

        txt_SGST.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_SGST.setText("Amount");
        panelRecieptDate.add(txt_SGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 411, 160, 35));
        panelRecieptDate.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 453, 250, 10));

        txt_TotalAmount.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_TotalAmount.setText("Amount");
        panelRecieptDate.add(txt_TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 463, 170, 35));

        txt_TotalInWords.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_TotalInWords.setText("Total In Words");
        panelRecieptDate.add(txt_TotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 463, 490, 35));

        lbl_TotalInWords.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_TotalInWords.setForeground(new java.awt.Color(245, 0, 31));
        lbl_TotalInWords.setText("Total In Words : ");
        panelRecieptDate.add(lbl_TotalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 463, -1, 35));

        lbl_GSTIN.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_GSTIN.setForeground(new java.awt.Color(245, 0, 31));
        lbl_GSTIN.setText("GSTIN : ");
        panelRecieptDate.add(lbl_GSTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, 35));

        txt_StudentRollNo.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_StudentRollNo.setText("Enrollment No. ");
        panelRecieptDate.add(txt_StudentRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 216, 180, 35));

        lbl_ReceiverSignature.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        lbl_ReceiverSignature.setText("Receiver Signature");
        panelRecieptDate.add(lbl_ReceiverSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 582, -1, -1));
        panelRecieptDate.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 565, 250, 10));

        txt_RecieptNoLogoPrefix.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_RecieptNoLogoPrefix.setText("SRIT-");
        panelRecieptDate.add(txt_RecieptNoLogoPrefix, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 42, -1, 35));

        lbl_Semester.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Semester.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Semester.setText("Semester : ");
        panelRecieptDate.add(lbl_Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, 35));

        txt_Semester.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Semester.setText("Semester : ");
        panelRecieptDate.add(txt_Semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 150, 35));

        lbl_Remark.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Remark.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Remark.setText("Remark : ");
        panelRecieptDate.add(lbl_Remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 516, -1, 35));

        txt_Remark.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Remark.setText("Remark");
        panelRecieptDate.add(txt_Remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 516, 510, 40));

        lbl_Date.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        lbl_Date.setForeground(new java.awt.Color(245, 0, 31));
        lbl_Date.setText("Date : ");
        panelRecieptDate.add(lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, 35));

        txt_Date.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        txt_Date.setText("Date : ");
        panelRecieptDate.add(txt_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, 35));

        panelToPrint.add(panelRecieptDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 199, 1027, 647));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelsideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr = new Color(0, 145, 145);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr = new Color(0, 102, 102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color clr = new Color(61, 85, 100);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr = new Color(51, 51, 51);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        Color clr = new Color(255, 51, 51);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        Color clr = new Color(204, 0, 51);
        jPanel11.setBackground(clr);
    }//GEN-LAST:event_jLabel9MouseExited

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        Color clr = new Color(0, 142, 255);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        Color clr = new Color(0, 102, 255);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);

                panelToPrint.print(g2);

                return Printable.PAGE_EXISTS;

            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        Color clr = new Color(3, 54, 170);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        Color clr = new Color(3, 53, 106);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_Amount;
    private javax.swing.JLabel lbl_BankName;
    private javax.swing.JLabel lbl_CGST;
    private javax.swing.JLabel lbl_ChequeNo_DDNo_TransactionId;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_GSTIN;
    private javax.swing.JLabel lbl_Head;
    private javax.swing.JLabel lbl_PaymentMode;
    private javax.swing.JLabel lbl_ReceiverSignature;
    private javax.swing.JLabel lbl_RecieptNo;
    private javax.swing.JLabel lbl_Remark;
    private javax.swing.JLabel lbl_SGST;
    private javax.swing.JLabel lbl_Semester;
    private javax.swing.JLabel lbl_SrNo;
    private javax.swing.JLabel lbl_StudentName;
    private javax.swing.JLabel lbl_StudentRollNo;
    private javax.swing.JLabel lbl_TotalInWords;
    private javax.swing.JLabel lbl_Year;
    private javax.swing.JLabel lbl_Year_Desh;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelRecieptDate;
    private javax.swing.JPanel panelRecieptLogo;
    private javax.swing.JPanel panelToPrint;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_Amount;
    private javax.swing.JLabel txt_BankName;
    private javax.swing.JLabel txt_CGST;
    private javax.swing.JLabel txt_ChequeNo_DDNo_TransactionId;
    private javax.swing.JLabel txt_CourseName;
    private javax.swing.JLabel txt_Date;
    private javax.swing.JLabel txt_GSTIN;
    private javax.swing.JLabel txt_PaymentMode;
    private javax.swing.JLabel txt_RecieptNo;
    private javax.swing.JLabel txt_RecieptNoLogoPrefix;
    private javax.swing.JLabel txt_Remark;
    private javax.swing.JLabel txt_SGST;
    private javax.swing.JLabel txt_Semester;
    private javax.swing.JLabel txt_SrNo;
    private javax.swing.JLabel txt_StudentName;
    private javax.swing.JLabel txt_StudentRollNo;
    private javax.swing.JLabel txt_TotalAmount;
    private javax.swing.JLabel txt_TotalInWords;
    private javax.swing.JLabel txt_Year1;
    private javax.swing.JLabel txt_Year2;
    // End of variables declaration//GEN-END:variables
}
